version: "3.8"
services:
  frontend:
    image: kooldev/node:20
    command: ["npm", "run", "dev", "--", "-p", "${FRONTEND_PORT:-3000}"]
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    environment:
      ASUSER: "${ASUSER:-0}"
      UID: "${UID:-0}"
      FRONTEND_PORT: "${FRONTEND_PORT:-3000}"
    volumes:
      - ./frontend:/app:delegated
    networks:
      - elixirr_local
  backend:
    image: kooldev/php:8.3-nginx
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      ASUSER: "${ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - ./backend:/app:delegated
    networks:
      - elixirr_local
  database:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${DATABASE_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD-rootpass}"
      MYSQL_DATABASE: "${DB_DATABASE-database}"
      MYSQL_USER: "${DB_USERNAME-user}"
      MYSQL_PASSWORD: "${DB_PASSWORD-pass}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database:/var/lib/mysql:delegated
    networks:
      - elixirr_local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
networks:
  elixirr_local:
volumes:
  database:
